#!/bin/sh
#
# Script to configure and start a L2TP/IPsec VPN server
#
# THIS SCRIPT IS ONLY MEANT TO BE RUN IN A UBUNTU PC WITH
# STRONGSWAN 5.5.2
#
# Copyright (C) 2016-2018 Lin Song <marzouk.souhaieb@gmail.com>
#
# This work is licensed by Sagemcom
#
# Attribution required: please include my name in any derivative and let me
# know how you have improved it!
# https://linux2me.wordpress.com/2016/05/20/pppoe-server-setup-in-ubuntu/

INTERFACE=$1
POOLIP=$2
POOLNETWORK=$(echo $2 | sed 's/\.[0-9]*$/\.'0'/')
INTERFACE2=$3
IPINTER2=$4

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

ifconfig $INTERFACE2 $IPINTER2/24 

cat > /etc/resolv.conf <<EOF
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF

cat > /etc/ppp/pppoe-server-options <<EOF
# PPP options for the PPPoE server
# LIC: GPL
debug
#plugin /etc/ppp/plugins/rp-pppoe.so
require-chap
require-pap
mtu 1492
mru 1492
ktune
proxyarp
lcp-echo-interval 10
lcp-echo-failure 2
nobsdcomp
noccp
novj
noipx
EOF

touch /etc/ppp/allip
cat > /etc/ppp/allip <<EOF
$POOLIP
EOF

iptables -t nat -A POSTROUTING -s $POOLNETWORK/24 -o $INTERFACE -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_forward
sysctl -p
pppoe-server -C isp -L $IPINTER2 -p /etc/ppp/allip -I $INTERFACE2
iptables -t nat -A POSTROUTING -s $POOLNETWORK/24 -o $INTERFACE -j MASQUERADE